default: &default
  adapter: redis

development:
  <<: *default
  url: redis://localhost:6379/2

test:
  <<: *default
  url: redis://localhost:6379/1

production:
  <<: *default
  url: redis://localhost:6379/3
  # channel_prefix: tower-demo_production
